SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
INNER JOIN CAR_RENTAL_COMPANY_CAR AS C
ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '세단' AND MONTH(H.START_DATE) = '10'
GROUP BY C.CAR_ID
ORDER BY C.CAR_ID DESC